include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    use_key_in_widget_constructors: ignore
    use_rethrow_when_possible: ignore
    avoid_print: ignore
    # must_be_immutable: error #non final fields should be error
    # must_call_super: error
    # invalid_use_of_protected_member: error
    # parameter_assignments: error 
    # sort_unnamed_constructors_first: ignore
    # sort_pub_dependencies: ignore
    # require_trailing_commas: ignore
    # directives_ordering: ignore
    # eol_at_end_of_file: ignore
