name: music_management_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.1
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.0.6
  flutter_bloc: ^7.3.3
  rxdart: ^0.27.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/place_holders/album_placeholder.jpg
    - assets/place_holders/stylus_album_placeholder.jpg

  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Black.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-BlackItalic.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Bold.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-BoldItalic.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ExtraBold.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ExtraLight.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Italic.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Light.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-LightItalic.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Medium.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-MediumItalic.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-SemiBold.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Thin.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ThinItalic.ttf

