name: music_management_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.1
  hooks_riverpod: ^1.0.0
  json_annotation: ^4.3.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.0.1
  build_runner: ^2.1.4



flutter:
  uses-material-design: true
