@baseurl = http://ws.audioscrobbler.com/2.0/
@token = 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
@acceptHeader = application/vnd.github.v3.html+json

@apiKey = f7712593a5a88903f6355b4509528151


GET {{baseurl}}/user/starred
  ?page=1
Authorization: bearer {{token}}
Accept: {{acceptHeader}}

###
GET {{baseurl}}?method=artist.search&artist=cher&limit=2
&api_key={{apiKey}}
&format=json



